/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uicomponents;

import java.awt.Image;
import java.io.File;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.EmployeeDetails;
import model.EmployeeHistory;

/**
 *
 * @author foram
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    EmployeeHistory history;
    public CreateJPanel(EmployeeHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        EmpNameLbl = new javax.swing.JLabel();
        EmpIdLbl = new javax.swing.JLabel();
        AgeLbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        StartDateLbl = new javax.swing.JLabel();
        LevelLbl = new javax.swing.JLabel();
        TeamInfoLbl = new javax.swing.JLabel();
        PositionTitleLbl = new javax.swing.JLabel();
        CellLbl = new javax.swing.JLabel();
        empName = new javax.swing.JTextField();
        empId = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        startDate = new javax.swing.JTextField();
        level = new javax.swing.JTextField();
        teamInfo = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        phoneNo = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        CreateEmployee = new javax.swing.JButton();
        EmailLbl = new javax.swing.JLabel();
        displayPhoto = new javax.swing.JButton();
        uploadPhoto = new javax.swing.JLabel();
        dropdown = new javax.swing.JComboBox<>();

        Title.setFont(new java.awt.Font("Lao MN", 1, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Create Employee");

        EmpNameLbl.setText("Employee Name:");

        EmpIdLbl.setText("Employee Id:");

        AgeLbl.setText("Age:");

        GenderLbl.setText("Gender");

        StartDateLbl.setText("Start Date:");

        LevelLbl.setText("Level:");

        TeamInfoLbl.setText("Team Info:");

        PositionTitleLbl.setText("Position Title:");

        CellLbl.setText("Cell Phone Number:");

        empName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNameActionPerformed(evt);
            }
        });

        startDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateActionPerformed(evt);
            }
        });

        CreateEmployee.setText("Create Employee");
        CreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateEmployeeActionPerformed(evt);
            }
        });

        EmailLbl.setText("Email Address:");

        displayPhoto.setText("Upload Photo");
        displayPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPhotoActionPerformed(evt);
            }
        });

        dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Female", "Male", "Others" }));
        dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmpNameLbl)
                    .addComponent(StartDateLbl)
                    .addComponent(GenderLbl)
                    .addComponent(AgeLbl)
                    .addComponent(EmpIdLbl)
                    .addComponent(displayPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empId, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(age, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dropdown, 0, 143, Short.MAX_VALUE)
                    .addComponent(uploadPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PositionTitleLbl)
                    .addComponent(TeamInfoLbl)
                    .addComponent(LevelLbl)
                    .addComponent(CellLbl)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EmailLbl)
                        .addGap(45, 45, 45)))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(level, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(teamInfo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(position, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email))
                .addGap(141, 141, 141))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(CreateEmployee)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpNameLbl)
                            .addComponent(empName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpIdLbl)
                            .addComponent(empId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgeLbl)
                            .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GenderLbl)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartDateLbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LevelLbl)
                            .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeamInfoLbl)
                            .addComponent(teamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PositionTitleLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CellLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLbl))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uploadPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CreateEmployee)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void empNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empNameActionPerformed

    private void startDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateActionPerformed

    private void CreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEmployeeActionPerformed

        boolean isDataValidated = true;
        if (!phoneNo.getText().isEmpty()) {
            if (phoneNo.getText().length() != 10) {
                JOptionPane.showMessageDialog(this, "Cell phone number Invalid");
                isDataValidated = false;
            }
        }
        if (!startDate.getText().isEmpty()) {
            if (startDate.getText().length() != 8) {
                JOptionPane.showMessageDialog(this, "Invalid Start Date");
                isDataValidated = false;
            }
        }
        String sc = " ,!#$%^&*()<+>=-_;:'";
        if (!email.getText().isEmpty()) {
            if ((!email.getText().endsWith("@gmail.com")) || ((email.getText().startsWith(sc)) || (email.getText().contains(sc)))) {
                JOptionPane.showMessageDialog(this, "Email Invalid");
                isDataValidated = false;
            }
        }
        
        if (isDataValidated) {
           DateTimeFormatter df = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String name = empName.getText();
            String id = empId.getText();
            int ageOfEmp = Integer.parseInt(age.getText());
            String genderEmp = (String) dropdown.getSelectedItem();
            System.out.print(genderEmp);
            String startingDate = startDate.getText();         
            String lev = level.getText();
            String teamInformation = teamInfo.getText();
            String pos = position.getText();
            String emailAdd = email.getText();
            long cellNo = Long.parseLong(phoneNo.getText());
            ImageIcon dPhoto = (ImageIcon) uploadPhoto.getIcon();

            EmployeeDetails eh = history.addNewProfile();

            eh.setEmpName(name);
            eh.setEmpId(id);
            eh.setAge(ageOfEmp);
            eh.setGender(genderEmp);
            eh.setStartDate(startingDate);
            eh.setLevel(lev);
            eh.setTeamInfo(teamInformation);
            eh.setPositionTitle(pos);
            eh.setPhoneNo(cellNo);
            eh.setEmailId(emailAdd);
            eh.setPhoto(dPhoto);

            JOptionPane.showMessageDialog(this, "Employee Details are saved!");
        }
    }//GEN-LAST:event_CreateEmployeeActionPerformed

    private void displayPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPhotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChoose = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Supports 3 extensions", "jpg", "jpeg", "png");
        fileChoose.setFileFilter(filter);
        int select = fileChoose.showOpenDialog(null);

        if (select == JFileChooser.APPROVE_OPTION) {
            File file = fileChoose.getSelectedFile();
            String getImage = file.getAbsolutePath();
            ImageIcon img = new ImageIcon(getImage);

            Image imgFit = img.getImage();
            Image imageFit = imgFit.getScaledInstance(uploadPhoto.getWidth(), uploadPhoto.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon format = new ImageIcon(imageFit);
            uploadPhoto.setIcon(format);
        }
    }//GEN-LAST:event_displayPhotoActionPerformed

    private void dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==dropdown){
            dropdown.getSelectedItem();
        }
    }//GEN-LAST:event_dropdownActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeLbl;
    private javax.swing.JLabel CellLbl;
    private javax.swing.JButton CreateEmployee;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JLabel EmpIdLbl;
    private javax.swing.JLabel EmpNameLbl;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel LevelLbl;
    private javax.swing.JLabel PositionTitleLbl;
    private javax.swing.JLabel StartDateLbl;
    private javax.swing.JLabel TeamInfoLbl;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField age;
    private javax.swing.JButton displayPhoto;
    private javax.swing.JComboBox<String> dropdown;
    private javax.swing.JTextField email;
    private javax.swing.JTextField empId;
    private javax.swing.JTextField empName;
    private javax.swing.JTextField level;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JTextField position;
    private javax.swing.JTextField startDate;
    private javax.swing.JTextField teamInfo;
    private javax.swing.JLabel uploadPhoto;
    // End of variables declaration//GEN-END:variables

}
